name: ci-test 

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup go 1.x 
        uses: actions/setup-go@v4
        id: go 

      - name: Check out code into the go module directory
        uses: actions/checkout@v3

      - name: Run Migrations
        uses: make migrateup

      - name: Test
        run: make test 

        
